language: csharp
dist: xenial
sudo: true
solution: "TinyBCT.sln"
install:
  - sudo apt-get install z3
  - (cd .. && git clone https://github.com/boogie-org/corral.git && cd corral && git submodule init && git submodule update && msbuild cba.sln && ln -s $(which z3) ./bin/Debug/z3.exe)
  - ./mono/build-deps.sh
  - travis_retry nuget restore ${TRAVIS_SOLUTION}
  - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
  - msbuild ${TRAVIS_SOLUTION}
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./TinyBCT/bin/Debug/TinyBCT.exe
