language: csharp
dist: xenial
sudo: true
solution: "TinyBCT.sln"
install:
  - (cd .. && wget -nv https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip && unzip z3-*.zip **/z3)
  - (cd .. && git clone https://github.com/boogie-org/corral.git && cd corral && git submodule init && git submodule update && msbuild cba.sln)
  - (cd .. && ln -s $(cd z3-*/bin && pwd)/z3 corral/bin/Debug/z3.exe)
  - travis_retry nuget restore ${TRAVIS_SOLUTION}
  - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
env:
  - MONO_IOMAP=all
script:
  - msbuild ${TRAVIS_SOLUTION}
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./NUnitTests/bin/Debug/NUnitTests.dll
